language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - phpenv config-add test/resources/php.ini

install:
  - composer install -o

script:
  - vendor/bin/phing travis

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 428df59ec23d3fc358359be1436f4fec0df6e77ca5f4353fdd7b88d5df220e28

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/acdad6e84d56bd5d896f    
    on_success: change
    on_failure: always
    on_start: never
